Repository taco-official/klkl-client, pull requests merged in 2024-09, with the labels that each got.

#29 refactor(KL-147): improve structure of Components
  src/components/PreviewContent/PreviewContent.style.js
  src/hooks/useTagQuery.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/FeedPage.style.js
  src/pages/FeedPage/components/AdditionalFilter/AdditionalFilter.jsx
  src/pages/FeedPage/components/AdditionalFilter/TagDataFetcher.jsx
  src/pages/FeedPage/components/AdditionalFilter/TagDataStatusRenderer.jsx
  src/pages/FeedPage/components/AdditionalFilter/TagSwitch.jsx
  src/pages/FeedPage/components/BasicFilter/BasicFilter.style.js
  src/pages/FeedPage/components/BasicFilter/CategorySection.jsx
  src/pages/FeedPage/components/BasicFilter/CitySection.jsx
  src/pages/FeedPage/components/BasicFilter/CountrySection.jsx
  src/pages/FeedPage/components/BasicFilter/SubCategoryArray.jsx
  src/pages/FeedPage/components/ProductList/ProductDataFetcher.jsx
  src/pages/FeedPage/components/ProductList/ProductDataStatusRenderer.jsx
  src/pages/FeedPage/components/ProductList/ProductList.jsx
  src/pages/FeedPage/components/SelectedField/ResetButton.jsx
  src/pages/FeedPage/components/SelectedField/SortButton.jsx
Labels: ♻️ Refactor, 💄 Style

#33 feat(KL-160/사진api연결): 사진 업로드 로직 추가
  src/hooks/useInitialData.js
  src/hooks/useReviewSubmit.js
  src/index.js
  src/loader/productLoader.js
  src/pages/ReviewPage/ReviewImageBlock.jsx
  src/pages/ReviewPage/ReviewPage.jsx
  src/pages/SubmitPage/SubmitPage.jsx
  src/pages/SubmitPage/components/ImageSubmit/ImageSubmitForm.jsx
  src/pages/SubmitPage/components/PostPage.jsx
  src/stores/useFormStore.js
Labels: ✨ Feature

#34 feat(KL-147): reset selected states on unmount FeedPage
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/components/ProductList/ProductDataStatusRenderer.jsx
Labels: ✨ Feature

#35 refactor(KL-159/리팩토링): fix notification, change designs
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentInput.jsx
  src/components/Navbar/components/SearchModal.jsx
  src/components/Notification/NotificationContent.jsx
  src/components/Notification/NotificationHeader.jsx
  src/components/UserProfile/UserProfile.jsx
  src/hooks/useDebouncedSearch.js
  src/hooks/useDeleteNotificationAll.js
  src/hooks/useNewReview.js
  src/hooks/useNotificationFetch.js
  src/hooks/usePopularReview.js
  src/hooks/useReadNotificationAll.js
  src/pages/ReviewPage/ReviewImageBlock.jsx
  src/pages/ReviewPage/ReviewInfo.jsx
  src/pages/ReviewPage/ReviewMiddle.jsx
  src/pages/ReviewPage/ReviewOptions.jsx
  src/pages/ReviewPage/ReviewPage.jsx
  src/pages/SubmitPage/components/ImageSubmit/ImageSubmitForm.jsx
  src/pages/SubmitPage/components/InfoSubmit/CurrencyList.jsx
  src/pages/SubmitPage/components/InfoSubmit/DescriptionInput.jsx
  src/pages/SubmitPage/components/InfoSubmit/InfoSubmit.jsx
  src/pages/SubmitPage/components/InfoSubmit/NameInput.jsx
  src/pages/SubmitPage/components/InfoSubmit/NumberInputForm.jsx
  src/pages/SubmitPage/components/InfoSubmit/RatingInput.jsx
  src/pages/SubmitPage/components/RegionSubmit/SelectionList.jsx
  src/pages/UserPage/ProductList.jsx
Labels: ♻️ Refactor

#37 refactor(KL-162): refactor FeedPage
  .gitignore
  src/components/Button/IconTextButton.jsx
  src/components/Button/LikeButton.jsx
  src/components/PreviewContent/PreviewContent.jsx
  src/components/PreviewContent/PreviewContent.style.js
  src/pages/FeedPage/components/BasicFilter/CitySection.jsx
  src/pages/FeedPage/components/BasicFilter/CountrySection.jsx
  src/pages/FeedPage/components/Thumbnail/Thumbnail.jsx
  src/pages/FeedPage/components/Thumbnail/Thumbnail.style.js
Labels: ⚙️ Chore, ♻️ Refactor

#36 refactor(KL-159/리팩토링): 바뀐 api에 맞춰 로직 수정했습니다
  src/hooks/useInitialData.js
  src/hooks/useReviewSubmit.js
  src/pages/ReviewPage/ReviewImageBlock.jsx
  src/pages/ReviewPage/ReviewPage.jsx
  src/pages/SubmitPage/components/CategorySubmit/CategorSubmitForm.jsx
  src/pages/SubmitPage/components/CategorySubmit/CategoryList.jsx
  src/pages/SubmitPage/components/CategorySubmit/CategorySelectList.jsx
  src/pages/SubmitPage/components/CategorySubmit/SubcategoryList.jsx
  src/pages/SubmitPage/components/CategorySubmit/TagSelectForm.jsx
  src/pages/SubmitPage/components/RegionSubmit/AddressInputForm.jsx
  src/pages/SubmitPage/components/RegionSubmit/CityList.jsx
  src/pages/SubmitPage/components/RegionSubmit/ContinentList.jsx
  src/pages/SubmitPage/components/RegionSubmit/CountryList.jsx
  src/pages/SubmitPage/components/RegionSubmit/RegionSelectForm.jsx
  src/pages/SubmitPage/components/RegionSubmit/RegionSelectList.jsx
  src/pages/SubmitPage/components/RegionSubmit/RegionSubmitForm.jsx
  src/pages/SubmitPage/components/RegionSubmit/SelectionList.jsx
  src/stores/useFormStore.js
  src/utils/uploadToS3.js
Labels: ♻️ Refactor

#38 fix(KL-162): modify property name of data
  src/components/PreviewContent/PreviewContent.jsx
Labels: 🐛 Bug

#42 fix(KL-159/리팩토링): api 변경사항에 맞춰 수정했습니다
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentList.jsx
  src/components/Comment/CommentListContent.jsx
  src/components/Navbar/components/LoginButton.jsx
  src/components/Notification/NotificationContent.jsx
  src/components/UserProfile/UserFollowButton.jsx
  src/components/UserProfile/UserProfile.jsx
  src/hooks/useInitialData.js
  src/pages/ReviewPage/LikeButton.jsx
  src/pages/ReviewPage/ReviewFloatButton.jsx
  src/pages/ReviewPage/ReviewImageBlock.jsx
  src/pages/ReviewPage/ReviewInfo.jsx
  src/pages/ReviewPage/ReviewPage.jsx
  src/pages/SubmitPage/components/CategorySubmit/CategorSubmitForm.jsx
  src/pages/SubmitPage/components/CategorySubmit/CategorySelectList.jsx
  src/pages/SubmitPage/components/CategorySubmit/TagSelectForm.jsx
  src/pages/SubmitPage/components/RegionSubmit/RegionSelectList.jsx
  src/pages/SubmitPage/components/RegionSubmit/RegionSubmitForm.jsx
  src/pages/UserEditPage/SaveButton.jsx
  src/pages/UserEditPage/UserEditPage.jsx
  src/pages/UserPage/FollowingList.jsx
  src/pages/UserPage/ReviewList.jsx
  src/pages/UserPage/UserPage.jsx
Labels: ⚙️ Chore, ♻️ Refactor

#47 feat(KL-173): reset location state for FeedPage
  src/pages/FeedPage/FeedPage.jsx
Labels: ✨ Feature

#46 feat(KL-169): apply Like API for preview
  src/components/Button/LikeButton.jsx
  src/components/PreviewContent/PreviewContent.jsx
  src/components/PreviewContent/PreviewContent.style.js
  src/components/ProductList/ProductList.jsx
  src/hooks/useInitializeState.js
Labels: ✨ Feature, ✅ Test

#51 fix(KL-175): add dependency when searching in FeedPage
  src/hooks/useInitializeState.js
  src/pages/FeedPage/FeedPage.jsx
Labels: 🐛 Bug

#52 feat(KL-178): apply mutate async
  src/components/Button/CollapseButton.jsx
  src/components/Button/IconTextButton.jsx
  src/components/Button/LikeButton.jsx
  src/components/Button/ShowHideButton.jsx
  src/components/PreviewContent/PreviewContent.jsx
  src/components/PreviewContent/PreviewContent.style.js
  src/pages/FeedPage/components/BasicFilter/CountrySection.jsx
Labels: ✨ Feature, ♻️ Refactor
