Repository taco-official/klkl-client, pull requests merged in 2024-10, with the labels that each got.

#54 refactor(KL-177): refactor pages
  src/components/Button/FloatingButton.jsx
  src/components/Button/LikeButton.jsx
  src/components/Button/MoreButton.jsx
  src/components/Button/PreviewLikeButton.jsx
  src/components/Button/SelectionField.jsx
  src/components/Button/TabletButton.jsx
  src/components/Comment/Comment.jsx
  src/components/Comment/CommentList.jsx
  src/components/Comment/CommentListContent.jsx
  src/components/Navbar/NavList.jsx
  src/components/Navbar/components/LoginButton.jsx
  src/components/Navbar/components/LoginModal.jsx
  src/components/Navbar/components/Notification.jsx
  src/components/Navbar/components/SearchModal.jsx
  src/components/PreviewContent/PreviewContent.jsx
  src/components/PreviewContent/PreviewContent.style.js
  src/components/ProductFeed/LoadingFeed.jsx
  src/components/ProductFeed/ProductFeed.jsx
  src/components/ProductFeed/ProductFeed.style.js
  src/components/ProductList/ProductDataStatusRenderer.jsx
  src/components/ProductList/ProductList.jsx
  src/components/UserProfile/UserFollowButton.jsx
  src/constants/initialPageData.js
  src/constants/navIndex.js
  src/constants/sortStandard.js
  src/constants/userMenuKeys.js
  src/hooks/useDebouncedSearch.jsx
  src/hooks/useFetchContent.jsx
  src/hooks/useInitializeState.js
  src/hooks/useKyQuery.js
  src/hooks/useNewReview.jsx
  src/hooks/useNotificationFetch.jsx
  src/hooks/usePopularReview.jsx
  src/hooks/useProductData.js
  src/hooks/useProductLike.js
  src/hooks/useProductQuery.js
  src/hooks/useUserData.js
  src/loader/meLoader.js
  src/loader/productEditLoader.js
  src/loader/userLoader.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/FeedPage.style.js
  src/pages/FeedPage/components/BasicFilter/BasicFilter.style.js
  src/pages/FeedPage/components/ProductDataRenderer.jsx
  src/pages/FeedPage/components/SelectedField/SortButton.jsx
  src/pages/HomePage/ReviewCarousel.jsx
  src/pages/ReviewPage/LikeButton.jsx
  src/pages/ReviewPage/ReviewFloatButton.jsx
  src/pages/ReviewPage/ReviewLikeButton.jsx
  src/pages/ReviewPage/ReviewPage.jsx
  src/pages/UserEditPage/SaveButton.jsx
  src/pages/UserPage/FollowingList.jsx
  src/pages/UserPage/MyPage.jsx
  src/pages/UserPage/ReviewList.jsx
  src/pages/UserPage/UserPage.jsx
  src/pages/index.js
  src/router.jsx
  src/stores/navbarStores.js
  src/stores/useFeedStore.js
  src/utils/parseQueryParams.js
Labels: 🐛 Bug, ♻️ Refactor, 💄 Style

#56 refactor(KL-159/리팩토링): managing login status
  jsconfig.json
  src/App.jsx
  src/components/Comment/CommentInput.jsx
  src/components/Navbar/NavList.jsx
  src/components/UserProfile/UserProfile.jsx
  src/hooks/kyInstance.js
  src/hooks/useUserData.js
  src/pages/Layout.jsx
  src/pages/UserPage/MyPage.jsx
  src/stores/useLoginStatus.js
Labels: 🐛 Bug

#61 fix(KL-185): fix logic for logout and refactor UserEditPage
  src/components/Comment/CommentEdit.jsx
  src/components/Comment/CommentInput.jsx
  src/components/Comment/CommentOptions.jsx
  src/components/Notification/NotificationContent.jsx
  src/components/UserProfile/UserEditButton.jsx
  src/components/UserProfile/UserFollowButton.jsx
  src/constants/kyMethod.js
  src/hooks/useDebouncedSearch.jsx
  src/hooks/useDeleteNotificationAll.js
  src/hooks/useKy.js
  src/hooks/useKyMutation.js
  src/hooks/useKyQuery.js
  src/hooks/useProductLike.js
  src/hooks/useReadNotificationAll.js
  src/hooks/useReviewSubmit.js
  src/hooks/useUserData.js
  src/loader/feedLoader.js
  src/loader/homeLoader.js
  src/loader/meLoader.js
  src/loader/productEditLoader.js
  src/loader/productLoader.js
  src/loader/userLoader.js
  src/pages/Layout.jsx
  src/pages/ReviewPage/ReviewOptions.jsx
  src/pages/SubmitPage/components/PostPage.jsx
  src/pages/UserEditPage/DescriptionInput.jsx
  src/pages/UserEditPage/NicknameInput.jsx
  src/pages/UserEditPage/ProfileEditBlock.jsx
  src/pages/UserEditPage/SaveButton.jsx
  src/pages/UserEditPage/UserEditPage.jsx
  src/stores/useUserStore.js
  src/utils/kyInstance.js
Labels: 🐛 Bug, ♻️ Refactor, 💄 Style

#70 feat(KL-159/리팩토링): add invalidation on github action
  .github/workflows/main.yml
  index.html
  src/components/Navbar/components/LoginButton.jsx
  src/images/favicon/android-icon-144x144.png
  src/images/favicon/android-icon-192x192.png
  src/images/favicon/android-icon-36x36.png
  src/images/favicon/android-icon-48x48.png
  src/images/favicon/android-icon-72x72.png
  src/images/favicon/android-icon-96x96.png
  src/images/favicon/apple-icon-114x114.png
  src/images/favicon/apple-icon-120x120.png
  src/images/favicon/apple-icon-144x144.png
  src/images/favicon/apple-icon-152x152.png
  src/images/favicon/apple-icon-180x180.png
  src/images/favicon/apple-icon-57x57.png
  src/images/favicon/apple-icon-60x60.png
  src/images/favicon/apple-icon-72x72.png
  src/images/favicon/apple-icon-76x76.png
  src/images/favicon/apple-icon-precomposed.png
  src/images/favicon/apple-icon.png
  src/images/favicon/browserconfig.xml
  src/images/favicon/favicon-16x16.png
  src/images/favicon/favicon-32x32.png
  src/images/favicon/favicon-96x96.png
  src/images/favicon/favicon.ico
  src/images/favicon/manifest.json
  src/images/favicon/ms-icon-144x144.png
  src/images/favicon/ms-icon-150x150.png
  src/images/favicon/ms-icon-310x310.png
  src/images/favicon/ms-icon-70x70.png
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/MainBanner.jsx
Labels: ⚙️ Chore

#72 fix(hotfix): fix logout logic
  src/components/UserProfile/UserEditButton.jsx
  src/hooks/useUserData.js
  src/pages/Layout.jsx
  src/pages/LogoutPage/LogoutPage.jsx
  src/pages/index.js
  src/router.jsx
Labels: 🐛 Bug, ♻️ Refactor

#73 feat(KL-176/배너 연결): link to FeedPage from MainBanner
  src/constants/defaultWallpaper.js
  src/hooks/useDebouncedSearch.jsx
  src/hooks/useInitializeLocationState.js
  src/hooks/useNavIndex.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/components/Thumbnail/Thumbnail.jsx
  src/pages/FeedPage/components/Thumbnail/Thumbnail.style.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/MainBanner.jsx
  src/pages/LogoutPage/LogoutPage.jsx
  src/utils/initializeSearchState.js
  src/utils/navigateWithState.js
Labels: ✨ Feature, ♻️ Refactor
